---
- name: Gather Interface Descriptions from IOS-XE
  hosts: HRT-90322-SW3
  gather_facts: false
  vars:
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Run show interface description command
      cisco.ios.ios_command:
        commands:
          - show interface description
      register: interface_output

    - name: Display the command output on the screen
      ansible.builtin.debug:
        var: interface_output.stdout_lines
